import { GasStation, CityConfig } from './types';

export const CITIES: Record<string, CityConfig> = {
  spain: {
    id: 'spain',
    name: 'España',
    country: 'España',
    currency: '€',
    unit: 'L',
    fuelTypes: [
      { id: 'G95 E5', label: 'G95 E5' },
      { id: 'G98 E5', label: 'G98 E5' },
      { id: 'DIÉSEL', label: 'DIÉSEL' },
      { id: 'DIÉSEL+', label: 'DIÉSEL+' },
    ],
    defaultFuel: 'G95 E5',
  },
  sf: {
    id: 'sf',
    name: 'San Francisco',
    country: 'United States',
    currency: '$',
    unit: 'gal',
    fuelTypes: [
      { id: 'UNL 87', label: 'UNL 87' },
      { id: 'PREM 91', label: 'PREM 91' },
      { id: 'DIESEL', label: 'DIESEL' },
    ],
    defaultFuel: 'UNL 87',
  },
};

export const MOCK_STATIONS: Record<'spain' | 'sf', GasStation[]> = {
  spain: [
    // Tenerife (provincia 38)
    {
      id: 'tf-1',
      name: 'Repsol Santa Cruz',
      brand: 'repsol',
      address: 'Autopista TF-1, Km 5',
      municipality: 'Santa Cruz de Tenerife',
      distance: 1.2,
      latitude: 28.46964,
      longitude: -16.3959,
      provinciaId: '38',
      provinciaNombre: 'Santa Cruz de Tenerife',
      prices: { 'G95 E5': 1.459, 'G98 E5': 1.612, 'DIÉSEL': 1.342, 'DIÉSEL+': 1.419 },
      isOpen: true,
      hours: 'Cierra a las 23:00',
    },
    {
      id: 'tf-2',
      name: 'Cepsa La Laguna',
      brand: 'cepsa',
      address: 'Av. los Menceyes, s/n',
      municipality: 'San Cristóbal de La Laguna',
      distance: 2.8,
      latitude: 28.4871,
      longitude: -16.3178,
      provinciaId: '38',
      provinciaNombre: 'Santa Cruz de Tenerife',
      prices: { 'G95 E5': 1.512, 'G98 E5': 1.654, 'DIÉSEL': 1.385, 'DIÉSEL+': 1.455 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'tf-3',
      name: 'Shell Puerto Cruz',
      brand: 'shell',
      address: 'Ctra. General del Botánico, 12',
      municipality: 'Puerto de la Cruz',
      distance: 4.5,
      latitude: 28.4116,
      longitude: -16.5451,
      provinciaId: '38',
      provinciaNombre: 'Santa Cruz de Tenerife',
      prices: { 'G95 E5': 1.689, 'G98 E5': 1.799, 'DIÉSEL': 1.512, 'DIÉSEL+': 1.599 },
      isOpen: false,
      hours: 'Cerrado • Abre a las 07:00 AM',
    },
    {
      id: 'tf-4',
      name: 'Disa Autovía',
      brand: 'disa',
      address: 'Autovía de San Andrés, Km 1',
      municipality: 'Santa Cruz de Tenerife',
      distance: 0.8,
      latitude: 28.4832,
      longitude: -16.2231,
      provinciaId: '38',
      provinciaNombre: 'Santa Cruz de Tenerife',
      prices: { 'G95 E5': 1.442, 'G98 E5': 1.595, 'DIÉSEL': 1.310, 'DIÉSEL+': 1.399 },
      isOpen: true,
      hours: 'Cierra a las 22:00',
    },
    {
      id: 'tf-5',
      name: 'BP El Mayorazgo',
      brand: 'bp',
      address: 'Subida al Mayorazgo, s/n',
      municipality: 'Santa Cruz de Tenerife',
      distance: 3.5,
      latitude: 28.4415,
      longitude: -16.2812,
      provinciaId: '38',
      provinciaNombre: 'Santa Cruz de Tenerife',
      prices: { 'G95 E5': 1.539, 'G98 E5': 1.679, 'DIÉSEL': 1.399, 'DIÉSEL+': 1.479 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'tf-6',
      name: 'Repsol Tacoronte',
      brand: 'repsol',
      address: 'Ctra. General del Norte, Km 16',
      municipality: 'Tacoronte',
      distance: 3.1,
      latitude: 28.4850,
      longitude: -16.4150,
      provinciaId: '38',
      provinciaNombre: 'Santa Cruz de Tenerife',
      prices: { 'G95 E5': 1.520, 'G98 E5': 1.662, 'DIÉSEL': 1.385, 'DIÉSEL+': 1.465 },
      isOpen: true,
      hours: 'Abierto de 06:00 a 22:00',
    },
    // Madrid (provincia 28)
    {
      id: 'md-1',
      name: 'Repsol Atocha',
      brand: 'repsol',
      address: 'Glorieta de Atocha, s/n',
      municipality: 'Madrid',
      distance: 0.0,
      latitude: 40.4065,
      longitude: -3.6908,
      provinciaId: '28',
      provinciaNombre: 'Madrid',
      prices: { 'G95 E5': 1.479, 'G98 E5': 1.629, 'DIÉSEL': 1.359, 'DIÉSEL+': 1.439 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'md-2',
      name: 'Cepsa Castellana',
      brand: 'cepsa',
      address: 'Paseo de la Castellana, 82',
      municipality: 'Madrid',
      distance: 1.1,
      latitude: 40.4378,
      longitude: -3.6918,
      provinciaId: '28',
      provinciaNombre: 'Madrid',
      prices: { 'G95 E5': 1.501, 'G98 E5': 1.648, 'DIÉSEL': 1.375, 'DIÉSEL+': 1.452 },
      isOpen: true,
      hours: 'Cierra a las 22:00',
    },
    {
      id: 'md-3',
      name: 'Shell Alcalá',
      brand: 'shell',
      address: 'Calle de Alcalá, 275',
      municipality: 'Madrid',
      distance: 2.3,
      latitude: 40.4351,
      longitude: -3.6532,
      provinciaId: '28',
      provinciaNombre: 'Madrid',
      prices: { 'G95 E5': 1.522, 'G98 E5': 1.671, 'DIÉSEL': 1.389, 'DIÉSEL+': 1.468 },
      isOpen: true,
      hours: 'Cierra a las 21:00',
    },
    {
      id: 'md-4',
      name: 'BP Gran Vía',
      brand: 'bp',
      address: 'Gran Vía, 54',
      municipality: 'Madrid',
      distance: 1.8,
      latitude: 40.4203,
      longitude: -3.7055,
      provinciaId: '28',
      provinciaNombre: 'Madrid',
      prices: { 'G95 E5': 1.489, 'G98 E5': 1.639, 'DIÉSEL': 1.365, 'DIÉSEL+': 1.445 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'md-5',
      name: 'Disa Villaverde',
      brand: 'disa',
      address: 'Av. de Andalucía, Km 8',
      municipality: 'Madrid',
      distance: 5.2,
      latitude: 40.3568,
      longitude: -3.6815,
      provinciaId: '28',
      provinciaNombre: 'Madrid',
      prices: { 'G95 E5': 1.458, 'G98 E5': 1.601, 'DIÉSEL': 1.335, 'DIÉSEL+': 1.415 },
      isOpen: true,
      hours: 'Cierra a las 23:00',
    },
    // Barcelona (provincia 08)
    {
      id: 'bc-1',
      name: 'Repsol Diagonal',
      brand: 'repsol',
      address: 'Av. Diagonal, 501',
      municipality: 'Barcelona',
      distance: 0.0,
      latitude: 41.3916,
      longitude: 2.1606,
      provinciaId: '08',
      provinciaNombre: 'Barcelona',
      prices: { 'G95 E5': 1.492, 'G98 E5': 1.642, 'DIÉSEL': 1.369, 'DIÉSEL+': 1.449 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'bc-2',
      name: 'Cepsa Gran Via',
      brand: 'cepsa',
      address: 'Gran Via de les Corts Catalanes, 455',
      municipality: 'Barcelona',
      distance: 1.0,
      latitude: 41.3876,
      longitude: 2.1705,
      provinciaId: '08',
      provinciaNombre: 'Barcelona',
      prices: { 'G95 E5': 1.518, 'G98 E5': 1.661, 'DIÉSEL': 1.388, 'DIÉSEL+': 1.462 },
      isOpen: true,
      hours: 'Cierra a las 22:00',
    },
    {
      id: 'bc-3',
      name: 'Shell Meridiana',
      brand: 'shell',
      address: 'Av. Meridiana, 220',
      municipality: 'Barcelona',
      distance: 1.7,
      latitude: 41.4053,
      longitude: 2.1855,
      provinciaId: '08',
      provinciaNombre: 'Barcelona',
      prices: { 'G95 E5': 1.541, 'G98 E5': 1.685, 'DIÉSEL': 1.399, 'DIÉSEL+': 1.479 },
      isOpen: false,
      hours: 'Cerrado • Abre a las 07:00',
    },
    // Valencia (provincia 46)
    {
      id: 'vl-1',
      name: 'Repsol Puerto',
      brand: 'repsol',
      address: 'C/ del Puerto, 185',
      municipality: 'Valencia',
      distance: 0.0,
      latitude: 39.4602,
      longitude: -0.3402,
      provinciaId: '46',
      provinciaNombre: 'Valencia',
      prices: { 'G95 E5': 1.468, 'G98 E5': 1.618, 'DIÉSEL': 1.348, 'DIÉSEL+': 1.425 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'vl-2',
      name: 'BP Malvarrosa',
      brand: 'bp',
      address: 'Paseo Marítimo, 25',
      municipality: 'Valencia',
      distance: 1.4,
      latitude: 39.4752,
      longitude: -0.3289,
      provinciaId: '46',
      provinciaNombre: 'Valencia',
      prices: { 'G95 E5': 1.488, 'G98 E5': 1.635, 'DIÉSEL': 1.358, 'DIÉSEL+': 1.438 },
      isOpen: true,
      hours: 'Cierra a las 21:00',
    },
    // Sevilla (provincia 41)
    {
      id: 'sv-1',
      name: 'Cepsa Torneo',
      brand: 'cepsa',
      address: 'Ronda de Triana, 12',
      municipality: 'Sevilla',
      distance: 0.0,
      latitude: 37.3925,
      longitude: -5.9971,
      provinciaId: '41',
      provinciaNombre: 'Sevilla',
      prices: { 'G95 E5': 1.472, 'G98 E5': 1.622, 'DIÉSEL': 1.352, 'DIÉSEL+': 1.432 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    {
      id: 'sv-2',
      name: 'Shell Nervión',
      brand: 'shell',
      address: 'Av. de la Buhaira, 40',
      municipality: 'Sevilla',
      distance: 1.0,
      latitude: 37.3798,
      longitude: -5.9742,
      provinciaId: '41',
      provinciaNombre: 'Sevilla',
      prices: { 'G95 E5': 1.502, 'G98 E5': 1.652, 'DIÉSEL': 1.375, 'DIÉSEL+': 1.455 },
      isOpen: true,
      hours: 'Cierra a las 22:00',
    },
    // Bilbao (provincia 48)
    {
      id: 'bi-1',
      name: 'Repsol Bilbao',
      brand: 'repsol',
      address: 'Gran Vía de Don Diego López de Haro, 75',
      municipality: 'Bilbao',
      distance: 0.0,
      latitude: 43.2622,
      longitude: -2.9355,
      provinciaId: '48',
      provinciaNombre: 'Bizkaia',
      prices: { 'G95 E5': 1.485, 'G98 E5': 1.631, 'DIÉSEL': 1.362, 'DIÉSEL+': 1.442 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    // Zaragoza (provincia 50)
    {
      id: 'zg-1',
      name: 'Cepsa Paseo',
      brand: 'cepsa',
      address: 'Paseo de la Independencia, 29',
      municipality: 'Zaragoza',
      distance: 0.0,
      latitude: 41.6533,
      longitude: -0.8799,
      provinciaId: '50',
      provinciaNombre: 'Zaragoza',
      prices: { 'G95 E5': 1.465, 'G98 E5': 1.615, 'DIÉSEL': 1.342, 'DIÉSEL+': 1.422 },
      isOpen: true,
      hours: 'Cierra a las 23:00',
    },
    // Málaga (provincia 29)
    {
      id: 'ma-1',
      name: 'Shell Málaga',
      brand: 'shell',
      address: 'Av. de Andalucía, 15',
      municipality: 'Málaga',
      distance: 0.0,
      latitude: 36.7216,
      longitude: -4.4213,
      provinciaId: '29',
      provinciaNombre: 'Málaga',
      prices: { 'G95 E5': 1.459, 'G98 E5': 1.609, 'DIÉSEL': 1.338, 'DIÉSEL+': 1.418 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
    // Murcia (provincia 30)
    {
      id: 'mu-1',
      name: 'BP Murcia',
      brand: 'bp',
      address: 'Gran Vía del Escultor Salzillo, 40',
      municipality: 'Murcia',
      distance: 0.0,
      latitude: 37.9878,
      longitude: -1.1291,
      provinciaId: '30',
      provinciaNombre: 'Murcia',
      prices: { 'G95 E5': 1.472, 'G98 E5': 1.622, 'DIÉSEL': 1.351, 'DIÉSEL+': 1.431 },
      isOpen: true,
      hours: 'Cierra a las 22:00',
    },
    // Palma de Mallorca (provincia 07)
    {
      id: 'pm-1',
      name: 'Repsol Palma',
      brand: 'repsol',
      address: 'Av. Gabriel Roca, 35',
      municipality: 'Palma de Mallorca',
      distance: 0.0,
      latitude: 39.5731,
      longitude: 2.6420,
      provinciaId: '07',
      provinciaNombre: 'Illes Balears',
      prices: { 'G95 E5': 1.502, 'G98 E5': 1.652, 'DIÉSEL': 1.382, 'DIÉSEL+': 1.462 },
      isOpen: true,
      hours: 'Abierto 24 Horas',
    },
  ],
  sf: [
    {
      id: 'sf-1',
      name: 'FastFuel Station',
      brand: 'generic',
      address: '452 Market St',
      municipality: 'SOMA / Financial District',
      distance: 0.8,
      latitude: 37.7891,
      longitude: -122.4010,
      prices: {
        'UNL 87': 4.12,
        'PREM 91': 4.45,
        'DIESEL': 4.29,
      },
      isOpen: true,
      hours: 'Closes at 11:00 PM',
    },
    {
      id: 'sf-2',
      name: 'Valero Energy',
      brand: 'valero',
      address: '1200 Mission Blvd',
      municipality: 'Civic Center',
      distance: 1.2,
      latitude: 37.7701,
      longitude: -122.4133,
      prices: {
        'UNL 87': 4.15,
        'PREM 91': 4.49,
        'DIESEL': 4.35,
      },
      isOpen: true,
      hours: 'Open 24 Hours',
    },
    {
      id: 'sf-3',
      name: 'Shell Helix',
      brand: 'shell',
      address: '890 Howard St',
      municipality: 'Yerba Buena',
      distance: 1.5,
      latitude: 37.7836,
      longitude: -122.4042,
      prices: {
        'UNL 87': 4.19,
        'PREM 91': 4.55,
        'DIESEL': 4.39,
      },
      isOpen: true,
      hours: 'Closes at 10:00 PM',
      logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBiQhuV9FvE9rg19dXAHaRESys51DdG65jpOcwMoUdrc9XLL4Pb3Jph5Tbw8_zmsOSvrcglzmTHDvhhCagAvUrPRNF_SwHkHZGo6qNhEvWL7x0fQjAcxcRuh04XCnZPhD7QUoG-Rv75kWtwMbNOcNXKz7rXe5DPe32ghAWNlJyagCV6qZbkIKMmJpzGQNjWJroC4ogEGnI0ndQ9XzXXsyVP2YfL9ca8SmsZPHfo2U529JgIorIpgCrTkcip60rNr-nhEIAKhbs27Bs',
    },
    {
      id: 'sf-4',
      name: 'Chevron Tech Hub',
      brand: 'chevron',
      address: '303 2nd St',
      municipality: 'South Beach',
      distance: 1.9,
      latitude: 37.7854,
      longitude: -122.3961,
      prices: {
        'UNL 87': 4.21,
        'PREM 91': 4.89,
        'DIESEL': 4.45,
      },
      isOpen: true,
      hours: 'Open 24 Hours',
    },
    {
      id: 'sf-5',
      name: 'EcoGas Depot',
      brand: 'generic',
      address: '77 Beale St',
      municipality: 'Embarcadero',
      distance: 2.1,
      latitude: 37.7925,
      longitude: -122.3976,
      prices: {
        'UNL 87': 4.25,
        'PREM 91': 4.59,
        'DIESEL': 4.40,
      },
      isOpen: true,
      hours: 'Open 24 Hours',
    },
    {
      id: 'sf-6',
      name: '7-Eleven Fuel',
      brand: 'generic',
      address: '221 Main St',
      municipality: 'Rincon Hill',
      distance: 2.4,
      latitude: 37.7899,
      longitude: -122.3929,
      prices: {
        'UNL 87': 4.29,
        'PREM 91': 5.25,
        'DIESEL': 4.60,
      },
      isOpen: true,
      hours: 'Closes at 8:00 PM',
    },
    {
      id: 'sf-7',
      name: 'Arco Express',
      brand: 'generic',
      address: '1101 Fell St',
      municipality: 'Alamo Square',
      distance: 2.4,
      latitude: 37.7761,
      longitude: -122.4322,
      prices: {
        'UNL 87': 4.75,
        'PREM 91': 4.99,
        'DIESEL': 4.85,
      },
      isOpen: true,
      hours: 'Open 24 Hours',
    },
  ],
};
